---
- name: apt_update
  apt: update_cache=yes

- name: restart_sshd
  service:
    name: "{{ openssh_service }}"
    state: restarted

- name: update_tmux_plugin_perms
  file:
    path: /home/andy/.tmux/plugins
    owner: andy
    group: andy
    recurse: true

- name: update_vim_bundle_perms
  file:
    path: /home/andy/.vim/bundle
    owner: andy
    group: andy
    recurse: true
