# Load distro-specific variables
- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- block:
  ## User configs
  - import_tasks: users/andy.yml

  ## system setup
  - import_tasks: system_setup/tweaks.yml

  ## install software
  - import_tasks: software/codecs.yml
  - import_tasks: software/chromium.yml
  - import_tasks: software/firefox.yml
  - import_tasks: software/google_chrome.yml
  # - import_tasks: software/glimpse.yml
  - import_tasks: software/libreoffice.yml
  - import_tasks: software/misc_games.yml
  - import_tasks: software/misc_packages.yml
  - import_tasks: software/spotify.yml
  # - import_tasks: software/steam.yml
  # - import_tasks: software/syncthing.yml
  - import_tasks: software/vlc.yml

  rescue:
    - set_fact: task_failed=true
