# set up flatpak support
- name: system setup | tweaks | add flatpak support
  package:
    name: flatpak
    state: present

- name: system setup | tweaks | flatpak | add flathub remote
  tags: packages,flatpak,workstation-packages
  become_user: andy
  flatpak_remote:
    name: flathub
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    method: user
    state: present


# # set up snap support
# # Note: Not available in Arch currently as of 2020-09-15
# - name: system setup | tweaks | install snapd
#   package:
#     name: snapd
#     state: latest
#
# # Ensure core snap is installed
# - name: system setup | tweaks | install/update core snap
#   tags: packages,snap,todoist,workstation-packages
#   snap:
#     name:  core
#     state: present


# - name: system setup | tweaks | install xorg
#   tags: distro,distro-setup,packages,system,system-packages,workstation-packages
#   package:
#     name: xorg-server
#   when: ansible_distribution == "Archlinux"
#
# - name: system setup | tweaks | install nvidia gpu packages
#   tags: distro,distro-setup,packages,nvidia,system,system-packages,workstation-packages
#   package:
#     name:
#       - nvidia
#       - nvidia-lts
#       - nvidia-utils
#   when:
#     - gpu is defined
#     - gpu == "nvidia"

- name: system setup | tweaks | install vbox gpu packages
  tags: distro,distro-setup,packages,system,system-packages,vbox,workstation-packages
  package:
    name:
      - virtualbox-guest-utils
      - xf86-video-vmware
  when:
    - gpu is defined
    - gpu == "vbox"
